name: weather_tracker
description: A Flutter app to track weather and send push notifications

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_local_notifications: ^15.1.0+1
  intl: ^0.17.0
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets: 
  - assets/img/

